version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # MySQL root 계정의 비밀번호
      MYSQL_DATABASE: todomon         # 초기 생성할 데이터베이스 이름
      MYSQL_CHARSET: utf8mb4             # 기본 charset을 utf8mb4로 설정
      MYSQL_COLLATION: utf8mb4_unicode_ci # 기본 collation을 utf8mb4_unicode_ci로 설정
      TZ: Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3305:3306"  # 호스트의 3306 포트를 컨테이너의 3306 포트와 연결
    volumes:
      - mysql_data:/var/lib/mysql  # 데이터를 지속하기 위한 볼륨 설정
    networks:
      - spring-mysql-network

  todomon-app:
    image: todomon-app
    container_name: todomon-app-container
    ports:
      - "8080:8080"
      - "9292:9292"
    networks:
      - spring-mysql-network
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - spring-mysql-network
    depends_on:
      - todomon-app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - spring-mysql-network
    depends_on:
      - prometheus

networks:
  spring-mysql-network:
    driver: bridge

volumes:
  mysql_data:
  grafana_data:
