global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'todomon-app:9292' ]  # Spring Boot 앱의 컨테이너 또는 호스트 주소
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
