# prometheus-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
    
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: [ "prometheus-service.default:9090" ]
      - job_name: 'spring-boot-actuator'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'todomon-app-service.default:9290' ]  # Spring Boot 앱의 컨테이너 또는 호스트 주소